import { Link } from "react-router";
import type { ReactNode } from "react";

type LegalDocument = "privacy" | "terms" | "cookies";

const documents: Record<LegalDocument, { title: string; intro: string }> = {
  privacy: { title: "Privacy Policy", intro: "This draft explains how VistaBalayan handles personal information in the public tourism website and the authenticated municipal and establishment portal." },
  terms: { title: "Terms and Conditions", intro: "These draft terms govern use of VistaBalayan as a tourism discovery, reporting, and decision-support system." },
  cookies: { title: "Cookie Policy", intro: "This draft explains browser storage, cookies, and the consent controls used by VistaBalayan." },
};

const Section = ({ title, children }: { title: string; children: ReactNode }) => (
  <section className="rounded-3xl bg-white/65 p-5 shadow-sm sm:p-7">
    <h2 className="text-xl font-semibold text-[#193364]">{title}</h2>
    <div className="mt-3 space-y-3 text-sm leading-7 text-slate-700">{children}</div>
  </section>
);

function SharedHeader({ active }: { active: LegalDocument }) {
  return (
    <header className="rounded-3xl bg-[#193364] p-5 text-white shadow-xl sm:p-7">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <Link to="/" className="text-lg font-semibold">VistaBalayan</Link>
        <nav className="flex flex-wrap gap-x-4 gap-y-2 text-sm" aria-label="Legal pages">
          {(["privacy", "terms", "cookies"] as LegalDocument[]).map((document) => (
            <Link key={document} to={`/${document === "privacy" ? "privacy-policy" : document === "terms" ? "terms-and-conditions" : "cookie-policy"}`} className={active === document ? "font-bold underline" : "text-white/80 hover:text-white"}>
              {documents[document].title}
            </Link>
          ))}
        </nav>
      </div>
    </header>
  );
}

function PrivacyPolicy() {
  return <>
    <Section title="1. Who is responsible for the information?"><p>The intended data controller is the <strong>Municipal Tourism and Cultural Affairs Office of Balayan, Batangas, Philippines</strong>. Official legal name, office address, Data Protection Officer, privacy email, and telephone number remain <strong>[CONFIRM BEFORE PUBLICATION]</strong>. The system operator, hosting arrangement, and any formal data-processing agreements must also be confirmed.</p></Section>
    <Section title="2. Information the system handles"><ul className="list-disc space-y-2 pl-5"><li>Public listing information supplied by establishments, such as name, category, address, contact details, opening hours, website, amenities, descriptions, coordinates, and images. The current public retrieval uses broad field selection, so it must be changed to an explicit allowlist before production to prevent future administrative, permit, or internal fields from being exposed.</li><li>Public ratings and reviews, including the reviewer name, rating, optional comment, optional review photo, visitor token, and submission timestamp. Review-photo client behavior and the checked-in storage/database definitions require reconciliation; final moderation, visibility, file-size, and deletion rules remain to be confirmed.</li><li>Optional browser behavior stored locally for recommendations, such as viewed listings, category selections, and searches.</li><li>Optional browser location used to calculate nearby listings and route distances. The current client requests browser permission and does not intentionally submit the location to VistaBalayan; this must be confirmed against deployment configuration and provider logs.</li><li>Portal account data, profile and establishment association, authentication events, submitted visitor and accommodation reports, listing-management data, permit files, notification preferences, and push-subscription metadata.</li><li>Operational logs, device/browser information, error information, and security records generated by hosting, authentication, and API services.</li><li>Aggregate submitted-report values sent through the server-side AI endpoint to the configured Gemini provider to generate recommendations and anomalies. Personal data must not be included in prompts; this boundary requires continuing review. Generated recommendations, anomalies, and normalized insight results may also be stored in application tables or cache records, with retention and deletion periods still to be confirmed.</li></ul></Section>
    <Section title="3. Purposes and legal bases"><p>Information is used to publish tourism listings, receive and moderate ratings, provide maps and discovery features, authenticate authorized staff, receive official tourism reports, produce municipal analytics, operate notifications, protect the service, and provide decision-support insights.</p><p>Possible Philippine Data Privacy Act bases include consent, performance of an agreement, legal obligation, public authority/public interest, and legitimate interests. The controller must confirm the applicable basis for each processing activity, especially public reviews, report processing, AI processing, and geolocation.</p></Section>
    <Section title="4. Service providers and disclosures"><p>The implementation uses or references Supabase for database, authentication, and storage; Vercel for hosting/server functions; Google Maps for directions; OpenStreetMap for embedded maps; OSRM for route-distance requests; Gemini for server-side AI generation; and email/push providers for operational messages where configured. Exact providers, regions, subprocessors, data-transfer safeguards, and contracts must be confirmed before this draft becomes final. VistaBalayan should not sell personal information.</p></Section>
    <Section title="5. Retention and deletion procedure"><p><strong>Draft retention schedule — [CONFIRM PERIODS].</strong> Public reviews and photos should be retained only while needed for moderation and public display, subject to an approved moderation/archival period. Account, permit, visitor-report, and accommodation-report records should be retained according to municipal records, tourism reporting, audit, and legal requirements. Security logs, push subscriptions, AI caches, and local browser identifiers should have defined expiry periods.</p><ol className="list-decimal space-y-2 pl-5"><li>Submit a request to the confirmed privacy/DPO contact with the data subject’s identity and the specific account, review, photo, or record involved.</li><li>The office verifies identity and authority, logs the request, checks legal retention or audit holds, and determines whether correction, access, export, restriction, or deletion is permitted.</li><li>Approved deletion is removed from active views and applicable storage/database records, including associated photos and device subscriptions, with backups and legal holds handled under the approved schedule.</li><li>The office records the action and communicates the result or lawful reason for refusal within the period required by applicable law and its published procedure.</li></ol><p>The current application does not provide a complete self-service deletion workflow. Requests must therefore use the confirmed office/DPO process until an approved workflow is implemented.</p></Section>
    <Section title="6. Data subject rights"><p>Subject to applicable law and lawful exceptions, individuals may request notice, access, correction, objection, withdrawal of consent, restriction, deletion or blocking, data portability where applicable, and information about automated processing. Requests and complaints should be directed to the confirmed DPO first and may be escalated to the Philippine National Privacy Commission where appropriate.</p></Section>
    <Section title="7. Security and international transfers"><p>The application provides role-aware routes and server-side checks for protected functions, but client-side protection alone is not sufficient authorization. The actual Supabase Row Level Security, Storage policies, service-role boundaries, and permit-file access controls require verification. Provider credentials are intended to remain server-side. No online system is risk-free. The controller must document encryption, access reviews, incident response, breach notification, backup protection, vendor contracts, and any transfer of information outside the Philippines before final publication.</p></Section>
    <Section title="8. Changes and contact"><p>This draft may change after legal, municipal, vendor, and security review. Last reviewed: 7 October 2026. Contact: <strong>[CONFIRM OFFICIAL PRIVACY CONTACT]</strong>.</p></Section>
  </>;
}

function TermsAndConditions() {
  return <>
    <Section title="1. Draft status and acceptance"><p>These Terms and Conditions are a draft for review by the Municipal Tourism and Cultural Affairs Office and a qualified Philippine legal/privacy professional. By using VistaBalayan, users agree to follow these terms and applicable law. If the final terms differ, the published final version controls.</p></Section>
    <Section title="2. Permitted use"><p>The public website may be used to discover tourism establishments, view listing information, request directions, and submit honest ratings. Authorized officers and establishment staff may use the portal only for their assigned municipal or establishment duties and only through their own accounts.</p></Section>
    <Section title="3. User submissions"><p>Reviewers should provide accurate, lawful, non-defamatory content and must not upload unlawful, harmful, private, infringing, or abusive material. VistaBalayan may apply automated checks and may be able to moderate, hide, reject, or remove submissions, subject to the actual moderation controls and procedure adopted by the system owner. A reviewer grants the municipality the limited permission needed to store, review, display, and back up the submitted review and photo for the service’s tourism purpose, subject to applicable privacy law. Review-photo storage, visibility, and deletion behavior require verification.</p></Section>
    <Section title="4. Portal responsibilities"><p>Portal users must protect credentials, report suspected compromise, submit accurate reports, avoid unauthorized access, and not upload files they lack authority to process. Permit files and internal reports are not public content and must not be shared outside authorized municipal workflows.</p></Section>
    <Section title="5. Maps, listings, and AI outputs"><p>Listing information may be supplied or updated by establishments and may require correction. Map pins, routes, opening hours, and third-party information can be incomplete or outdated. AI-generated recommendations and anomaly descriptions are decision-support drafts, not official determinations, legal advice, or a substitute for officer review.</p></Section>
    <Section title="6. Availability and liability"><p>VistaBalayan may be unavailable, delayed, or affected by third-party services. To the extent permitted by law, the municipality is not responsible for losses caused by reliance on incomplete listings, third-party maps, route results, ratings, or AI outputs. Nothing in these terms removes rights or remedies that cannot lawfully be excluded.</p></Section>
    <Section title="7. Intellectual property and reports"><p>VistaBalayan software, branding, text, and original design are owned or used by the municipality or its licensors. Users retain rights they have in their submissions but provide the limited operational permission described above. Official reports remain subject to municipal records and public-disclosure rules.</p></Section>
    <Section title="8. Suspension, complaints, and governing law"><p>Access or content may be suspended where necessary for security, abuse prevention, moderation, legal compliance, or account administration. Report problems through <strong>[CONFIRM OFFICIAL SUPPORT CONTACT]</strong>. Governing law, venue, dispute handling, and the final authority responsible for these terms are <strong>[CONFIRM BEFORE PUBLICATION]</strong>.</p></Section>
  </>;
}

function CookiePolicy() {
  return <>
    <Section title="1. What this policy covers"><p>This policy covers cookies and similar browser storage used by the public tourism website and authenticated portal. A cookie is a small browser value sent with requests; localStorage is browser storage that is not automatically sent with every request.</p></Section>
    <Section title="2. Current storage categories"><ul className="list-disc space-y-2 pl-5"><li><strong>Essential:</strong> the consent record, Supabase client authentication storage where a user signs in, and any essential interface state such as a sidebar preference if that component is used. The anonymous rating visitor token is currently treated by the rating workflow as necessary for rating integrity, but its legal classification, retention, server-side enforcement, and effectiveness against abuse require privacy and security review. These items support operation but are not proof of strong identity verification.</li><li><strong>Preferences:</strong> local browser values for convenience features, including public discovery behavior, saved reviewer name, and other optional preferences. These are not advertising identifiers.</li><li><strong>Analytics:</strong> no third-party analytics tool was identified in the reviewed build. This category remains disabled unless a tool is separately approved, documented, and consent-gated.</li><li><strong>Third-party requests:</strong> maps, routing, directions, images, hosting, authentication, storage, and APIs may receive request metadata under their own policies. Review the provider list in the Privacy Policy before final publication.</li></ul></Section>
    <Section title="3. Consent controls"><p>The banner provides <strong>Accept All</strong>, <strong>Reject Optional</strong>, and <strong>Manage Preferences</strong>. Essential storage remains enabled. Optional categories are off until selected. The current consent choice is stored locally under a versioned key so the site can remember the choice; it is not used as an analytics profile. These controls do not by themselves prove that every optional storage operation is blocked in every deployed path; this requires testing.</p><p>Users can reopen the controls with the “Cookie settings” button. Browser settings can also clear or block storage, but doing so may affect authentication, consent memory, ratings, or site functionality.</p></Section>
    <Section title="4. Retention and changes"><p>Consent records should be refreshed at a documented interval of <strong>[CONFIRM CONSENT RENEWAL PERIOD]</strong> and whenever purposes or providers materially change. Local discovery and reviewer values remain on the device until cleared by the user or the site’s documented reset procedure. Server-side records and provider retention are governed by the Privacy Policy and must be assigned approved periods.</p></Section>
    <Section title="5. Contact"><p>Questions, withdrawal requests, and privacy complaints should be sent to <strong>[CONFIRM OFFICIAL PRIVACY CONTACT]</strong>. This draft was last reviewed on 7 October 2026 and requires qualified privacy-professional review.</p></Section>
  </>;
}

export default function LegalPage({ document }: { document: LegalDocument }) {
  const content = document === "privacy" ? <PrivacyPolicy /> : document === "terms" ? <TermsAndConditions /> : <CookiePolicy />;
  return (
    <main className="min-h-screen bg-[#E0E5EC] px-4 py-6 text-slate-900 sm:px-6 sm:py-10">
      <div className="mx-auto max-w-5xl space-y-5">
        <SharedHeader active={document} />
        <section className="rounded-3xl bg-[#E0E5EC] p-2 sm:p-4">
          <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#6C9772]">Draft for legal and municipal review</p>
          <h1 className="mt-3 text-4xl font-semibold tracking-tight text-[#193364] sm:text-5xl">{documents[document].title}</h1>
          <p className="mt-4 max-w-3xl text-base leading-7 text-slate-600">{documents[document].intro}</p>
          <p className="mt-3 text-sm font-semibold text-amber-700">This document is not legal advice and must not be treated as final until the marked facts, contacts, retention periods, vendors, and procedures are confirmed.</p>
        </section>
        <div className="space-y-4">{content}</div>
        <footer className="flex flex-wrap gap-x-5 gap-y-2 px-2 pb-6 text-sm text-slate-600">
          <Link to="/" className="font-semibold text-[#193364] underline">Back to VistaBalayan</Link>
          <span>© {new Date().getFullYear()} VistaBalayan — draft policies</span>
        </footer>
      </div>
    </main>
  );
}
